#!/bin/sh
# Ensure that our tests pass before pushing changes to our remote.
# We can override this by prefixing our HEAD commit with: "[FORCE COMMIT]"

if [ ! -z "$MAKE_IS_RUNNING" ]
then
  exit 0
fi
echo "INFO: Running pre-push tests. Please wait a moment."
if ! git log --pretty=format:"%s" -n 1 HEAD | grep -qE "^\[FORCE COMMIT\] "
then
  export UPDATE_TRAVIS=1
  # TODO: Add integration tests!
  for build_step in init  unit_tests
  do
    if ! make "$build_step"
    then
      echo "ERROR: Tests failed! If this is intentional, include \"[FORCE COMMIT]\" \
  to the beginning of your commit message." >&2
      exit 1
    fi
  done
fi

echo "INFO: All tests passed! Updating version prior to push."
