language: Bash
sudo: required
services:
  - docker
before_install:
  - docker pull ruby:2.4.2-alpine3.6
  - docker run -d -v $PWD:/work -w /work -p 127.0.0.1:5000:5000 ruby:2.4.2-alpine3.6 "bundle exec rake test"
script:
  - bundle exec rake test
after_success:
  - docker run -d -v $PWD:/work -w /work ruby:2.4.2-alpine3.6 "bundle exec rake deploy"
