language: Bash
sudo: required
services:
- docker
script:
- echo "I am running Make version $(make -v)."
- if [ "$TRAVIS_BRANCH" != "master" ]; then BUILD_ENVIRONMENT=integration make ci_build;
  fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then BUILD_ENVIRONMENT=production make ci_build
  && make deploy_app; fi
after_success:
- TERRAFORM_STATE_ENVIRONMENT=production make deploy_app
before_install:
- openssl aes-256-cbc -K $encrypted_342f2f6ad141_key -iv $encrypted_342f2f6ad141_iv
  -in env.tar.enc -out env.tar -d
- tar xvf env.tar
