language: Bash
sudo: required
dist: xenial
services:
- docker
script:
- echo "I am running Make version $(make -v)."
- make ci_build
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then make deploy_app; fi
before_install:
- sudo apt-get install make=4.1-6
- openssl aes-256-cbc -K $encrypted_342f2f6ad141_key -iv $encrypted_342f2f6ad141_iv
  -in env.tar.enc -out env.tar -d
- tar xvf env.tar
