language: Bash
sudo: required
dist: trusty
services:
- docker
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  echo "Integration ${TRAVIS_PULL_REQUEST_BRANCH} into ${TRAVIS_BRANCH}"; 
  ENVIRONMENT_ID=${TRAVIS_PULL_REQUEST} BUILD_ENVIRONMENT=integration /usr/bin/make ci_build; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" != "master" ]; then
  echo "Running local integration build."; BUILD_ENVIRONMENT=integration /usr/bin/make ci_build; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  echo "Deploying to production."; BUILD_ENVIRONMENT=production /usr/bin/make deploy; fi
before_install:
- openssl aes-256-cbc -K $encrypted_342f2f6ad141_key -iv $encrypted_342f2f6ad141_iv
  -in env.tar.enc -out env.tar -d
- sudo apt-get install --only-upgrade make
- tar xvf env.tar
