source 'https://rubygems.org'

gem 'aws-sdk'
gem 'colorize'
gem 'dotenv'
gem 'kramdown'
gem 'prawn'
gem 'prawn-table'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'rdoc'
gem 'rspec'
gem 'rspec-shell-expectations'
gem 'rubocop-rspec'
gem 'sinatra'
