# frozen_string_literal: true

module RSpecHelpers
  module Terraform
    def self.initialize
      unless File.exist?('terraform.tfplan.json')
        raise 'Terraform plan JSON not found.'
      end
      TerraformPlan.from_json(File.read('terraform.tfplan.json'))
    end

    # I'm not sure why this is triggering this cop. I'm guessing that
    # this has something to do with the RSpec verbs.
    # Therefore, I'm disabling it for now.
    # NOTE: I'm fully aware that this is better suited as an RSpec plugin.
    # There's really no way to reduce the Abc of this since the "it"
    # blocks can't be generated by methods.
    # rubocop:disable Metrics/AbcSize
    def self.run_tests(resource_name:,
                       test_definitions_hash: nil, **)
      if test_definitions_hash.nil?
        raise "Your test for #{resource_name} is missing a " \
'`test_definitions_hash`. Please define one.'
      end
      RSpec.describe 'Given a repository of Terraform configurations',
                     terraform: true do
        include TerraformTest
        context "When I define \"#{resource_name}\"" do
          it 'It should not be empty' do
            expect(@terraform_plan[resource_name]).not_to be_empty
          end
          test_definitions_hash.each_key do |resource_argument|
            test_definition = test_definitions_hash[resource_argument]
            example_name =
              RSpecHelpers::TerraformTest.create_example_name(test_definition,
                                                              resource_name,
                                                              resource_argument)
            it "It should have a value for argument: '#{resource_argument}'" do
              expect(
                RSpecHelpers::TerraformTest.resource_path_is_within_plan?(
                  plan: @terraform_plan,
                  resource_name: resource_name,
                  resource_arg: resource_argument
                )
              ).to be true
            end
            it example_name do
              expect(RSpecHelpers::TerraformTest.run_test(
                       test_definition: test_definition,
                       plan: @terraform_plan,
                       resource_name: resource_name,
                       resource_arg: resource_argument
              )).to eq 'Pass'
            end
          end
        end
      end
    end
    # rubocop:enable Metrics/AbcSize
  end
end
